spring:
  datasource:
    url: jdbc:h2:file:~/restdb
    driver-class-name: org.h2.Driver				
    hikari:
      username: sa
    
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api/v1